#
# Copyright (c) 2020-2024 Joel Winarske
#
# SPDX-License-Identifier: MIT
#

SUMMARY = "Flutter makes it easy and fast to build beautiful apps for mobile and beyond."
DESCRIPTION = "Flutter is Google's SDK for crafting beautiful, fast user experiences for \
               mobile, web, and desktop from a single codebase. Flutter works with \
               existing code, is used by developers and organizations around the world, \
               and is free and open source."
AUTHOR = "Google"
HOMEPAGE = "https://flutter.dev/"
BUGTRACKER = "https://github.com/flutter/flutter/issues"
SECTION = "graphics"
CVE_PRODUCT = ""

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=1d84cf16c48e571923f837136633a265"

DEPENDS += "\
    ca-certificates-native \
    curl-native \
    ninja-native \
    unzip-native \
    "

RDEPENDS:${PN} += "\
    atk \
    ca-certificates \
    curl \
    fontconfig \
    gtk+3 \
    pango \
    perl \
    perl-modules \
    unzip \
    "

require conf/include/flutter-version.inc

# The pub cache the SDK needs, as SRC_URI entries generated by
# tools/pubvendor from the archive's own flutter/pubspec.lock. The release
# archive ships bin/cache fully populated but no .pub-cache, and every app
# recipe copies the SDK's .pub-cache (common.inc do_archive_pub_cache), so it
# has to exist. Fetching it declaratively is what lets do_unpack run with no
# network. Regenerate on every roll; the lock checksum below is checked
# against the archive so a stale fragment fails loudly. See #711.
require recipes-graphics/flutter-sdk/flutter-sdk-pubcache.inc

PV = "${FLUTTER_SDK_VERSION}"

inherit pkgconfig

SRC_URI = "\
    https://storage.googleapis.com/flutter_infra_release/releases/${@get_flutter_archive(d)};name=flutter-sdk \
"
SRC_URI[flutter-sdk.sha256sum] = "${@get_flutter_sha256(d)}"

# No SRC_URI entry for the material fonts. One was here, with
# destsuffix=${D}.../bin/cache/artifacts/material_fonts, and it placed nothing:
# destsuffix is implemented by the git, hg, npm and npmsw fetchers only, and
# wget inherits the generic unpack, which honours subdir alone and ignores an
# unknown parameter. The files landed in ${WORKDIR} and were never installed.
#
# Placement would not have survived anyway -- do_unpack:append below removes
# ${S}/bin/cache, and ${D} does not exist at do_unpack. flutter_tools fetches
# the fonts itself during do_unpack, which is why the dead entry looked like it
# worked.
#
# Fetching precache artifacts declaratively is #711 and needs more than a
# placement parameter: somewhere that survives the rmtree, and a way to stop
# flutter_tools re-downloading.

S = "${UNPACKDIR}/flutter"

def getstatusoutput(cmd, cwd, env):
    from subprocess import check_output, CalledProcessError, STDOUT

    try:
        data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT, cwd=cwd, env=env)
        status = 0
    except CalledProcessError as ex:
        data = ex.output
        status = ex.returncode
    if data[-1:] == '\n':
        data = data[:-1]
    return status, data

def run_command(d, cmd, cwd, env):
    import subprocess
    import re

    # replace all consecutive whitespace characters (tabs, newlines etc.) with a single space
    cmd = re.sub(r'\s{2,}', ' ', cmd)

    bb.note('Running [%s] in %s' % (cmd, cwd))
    (retval, output) = getstatusoutput(cmd, cwd, env)
    if retval:
        bb.error("failed %s (cmd was %s)%s" % (retval, cmd, ":\n%s" % output if output else ""))
        return

    bb.note(f'{output}')


do_unpack[depends] += " \
    ca-certificates-native:do_populate_sysroot \
    curl-native:do_populate_sysroot \
    ninja-native:do_populate_sysroot \
    unzip-native:do_populate_sysroot \
"
python do_unpack:append() {
    import shutil

    # The release archive ships a populated bin/cache -- all 21 stamps plus the
    # artifacts -- so only the platforms we do not build are dropped. Deleting
    # the tree is what made flutter_tools re-download it. See #711.
    source_dir = d.getVar('S')
    import glob
    for pattern in ('android-*', 'ios*', 'darwin*', 'windows*'):
        for path in glob.glob(f'{source_dir}/bin/cache/artifacts/engine/{pattern}'):
            shutil.rmtree(path, ignore_errors=True)

    env = os.environ

    staging_dir_native = d.getVar('STAGING_DIR_NATIVE')
    env['CURL_CA_BUNDLE'] = f'{staging_dir_native}/etc/ssl/certs/ca-certificates.crt'

    path = env['PATH']
    env['PATH']           = f'{source_dir}/bin:{path}'
    env['PUB_CACHE']      = f'{source_dir}/.pub-cache'

    workdir = d.getVar('WORKDIR')
    # required for dart: https://github.com/dart-lang/sdk/issues/41560
    env['HOME'] = f'{workdir}'
    # required for flutter: https://github.com/flutter/flutter/issues/59430
    env['XDG_CONFIG_HOME'] = f'{workdir}'

    http_proxy = d.getVar('http_proxy')
    if http_proxy != None:
        env['http_proxy']     = f'{http_proxy}'

    https_proxy = d.getVar('https_proxy')
    if https_proxy != None:
        env['https_proxy']    = f'{https_proxy}'

    http_proxy_ = d.getVar('HTTP_PROXY')
    if http_proxy_ != None:
        env['HTTP_PROXY']     = f'{http_proxy_}'

    https_proxy_ = d.getVar('HTTPS_PROXY')
    if https_proxy_ != None:
        env['HTTPS_PROXY']    = f'{https_proxy_}'

    env['NO_PROXY']       = 'localhost,127.0.0.1,::1'

    flutter_sdk_tag = d.getVar('FLUTTER_SDK_TAG')
    bb.note(f'Flutter SDK: {flutter_sdk_tag}')

    run_command(d, 'flutter config --clear-features', source_dir, env)
    run_command(d, 'flutter config --enable-linux-desktop', source_dir, env)
    run_command(d, 'flutter config --enable-custom-devices', source_dir, env)
    run_command(d, 'flutter config --enable-web', source_dir, env)
    run_command(d, 'flutter config --no-analytics', source_dir, env)
    run_command(d, 'dart --disable-analytics', source_dir, env)
    run_command(d, 'flutter config --list', source_dir, env)

    # Stage the pub cache fetched through SRC_URI, then resolve against it.
    #
    # Measured at 3.47.5 under network isolation: the archive's
    # .dart_tool/package_config.json names 170 of its 248 package roots by
    # absolute path into the build bot's cache
    # (file:///b/s/w/ir/x/w/archive/.pub-cache/...), so nothing resolves until
    # it is rewritten. `dart pub get --offline` rewrites all 170 to ours and
    # returns "Got dependencies!" with no network. `flutter update-packages`
    # cannot be used for this: it reaches pub.dev/api/packages/<pkg>/advisories
    # regardless of --offline whenever pub's metadata cache holds a version
    # listing (see classes/pub-cache.bbclass and #860).
    #
    # Nothing here writes pub's .cache, so that path stays unreachable.
    # SRC_URI subdir= is relative to UNPACKDIR where that exists (styhead on)
    # and to WORKDIR before it, same fallback as classes/pub-cache.bbclass.
    unpackdir = d.getVar('UNPACKDIR') or d.getVar('WORKDIR')
    staged_cache = os.path.join(unpackdir, d.getVar('PUB_CACHE_LOCAL'))
    sdk_cache = f'{source_dir}/.pub-cache'
    if not os.path.isdir(staged_cache):
        bb.fatal('no pub cache at %s: flutter-sdk-pubcache.inc staged nothing'
                 % staged_cache)
    bb.utils.mkdirhier(sdk_cache)
    for name in os.listdir(staged_cache):
        shutil.move(os.path.join(staged_cache, name),
                    os.path.join(sdk_cache, name))

    # A roll that bumps FLUTTER_SDK_TAG without regenerating the fragment would
    # otherwise stage the previous release's packages and resolve against them.
    import hashlib
    with open(f'{source_dir}/pubspec.lock', 'rb') as f:
        lock_sha256 = hashlib.sha256(f.read()).hexdigest()
    expected = d.getVar('PUBSPEC_LOCK_SHA256')
    if lock_sha256 != expected:
        bb.fatal('flutter-sdk-pubcache.inc is stale: %s has sha256 %s, fragment '
                 'expects %s. Regenerate with tools/pubvendor.'
                 % (f'{source_dir}/pubspec.lock', lock_sha256, expected))

    env['PUB_CACHE'] = sdk_cache
    run_command(d, f'{source_dir}/bin/cache/dart-sdk/bin/dart pub get --offline',
                source_dir, env)

    # The resolve either rewrote every bot path or it did not work. An invalid
    # package_config.json does not fail any command here -- it just sends the
    # next pub invocation to the network -- so check rather than hope.
    package_config = f'{source_dir}/.dart_tool/package_config.json'
    with open(package_config) as f:
        contents = f.read()
    if '/b/s/w/ir' in contents:
        bb.fatal('%s still names the build bot pub cache after pub get --offline'
                 % package_config)

    # Not `flutter doctor`: it runs `dart pub --directory packages/flutter_tools
    # get` without --offline, so it reaches the network. Measured at 3.47.5 that
    # pub get was still running after 20 minutes with network available, and
    # with no network it fails while doctor still exits 0 -- tolerant, not
    # offline. The tool snapshot doctor would build ships in the archive
    # (bin/cache/flutter_tools.snapshot) and the resolve above is what makes it
    # usable. `flutter --version` exercises the same snapshot and returns at
    # once.
    run_command(d, 'flutter --version', source_dir, env)

}

do_install() {

    chmod a+rw ${S} -R

    install -d ${D}${datadir}/flutter/sdk

    cp -rTv ${S}/. ${D}${datadir}/flutter/sdk
}

do_install:append:class-target () {
    rm -rf ${D}${datadir}/flutter/sdk/bin/cache/artifacts/engine
    rm -rf ${D}${datadir}/flutter/sdk/bin/cache/dart-sdk/bin
}

# pub records where it resolved a package, and it records it absolutely: every
# package_config.json in the SDK names its dependencies as file:// URIs under
# ${S}, which is inside TMPDIR. Nothing recreates that path in a recipe that
# consumes the SDK -- there it lives under recipe-sysroot-native -- so all of
# those entries dangle, and the flutter tool concludes flutter_tools is
# unresolved and re-runs `dart pub get` on it. That resolve is not offline. It
# reaches pub.dev on every app build, and in a task with no network it does not
# fail, it hangs until something kills it.
#
# The URIs may be relative to the file that holds them, which flutter_tools'
# own entry ("../") already is. Making the rest relative makes the staged SDK
# relocatable, and takes an absolute TMPDIR out of a staged artifact while it
# is there. See #566.
python relativize_dart_package_configs() {
    import json
    import os
    import time
    import urllib.parse

    s_root = os.path.realpath(d.getVar('S'))
    sdk_root = d.getVar('D') + d.getVar('datadir') + '/flutter/sdk'

    for root, dirs, files in os.walk(sdk_root):
        if 'package_config.json' not in files:
            continue
        path = os.path.join(root, 'package_config.json')
        with open(path, 'r') as f:
            cfg = json.load(f)

        rewritten = 0
        foreign = []
        for pkg in cfg.get('packages', []):
            uri = pkg.get('rootUri', '')
            if not uri.startswith('file://'):
                continue
            abs_path = urllib.parse.unquote(urllib.parse.urlparse(uri).path)
            if abs_path != s_root and not abs_path.startswith(s_root + os.sep):
                # Outside the SDK entirely: relativizing would not help and
                # would hide it, so say so and leave it.
                foreign.append('%s -> %s' % (pkg.get('name'), uri))
                continue
            staged = os.path.join(sdk_root, os.path.relpath(abs_path, s_root))
            pkg['rootUri'] = os.path.relpath(staged, root)
            rewritten += 1

        if foreign:
            bb.warn('%s: %d package(s) resolved outside the SDK, left absolute: %s'
                    % (os.path.relpath(path, sdk_root), len(foreign),
                       ', '.join(foreign[:3])))
        if rewritten:
            with open(path, 'w') as f:
                json.dump(cfg, f, indent=2)
            bb.note('%s: made %d rootUri entries relative'
                    % (os.path.relpath(path, sdk_root), rewritten))

        # Make the resolution unambiguously newer than what it resolves.
        #
        # The flutter tool re-runs `pub get` on packages/flutter_tools when its
        # package_config.json does not look newer than the pubspec beside it --
        # and that resolve carries no --offline, so in a task with no network it
        # hangs until something kills it. Relative rootUris (above) stopped the
        # paths dangling; they do not say anything about freshness.
        #
        # do_install copies with `cp -rT`, which stamps mtimes at copy time in
        # traversal order, so which of the two ends up newer is not decided by
        # anything. sstate then preserves whatever it got, which is why the same
        # SDK can build clean once and hang the next time it is restored.
        #
        # Stamp it here instead, after the file is written, and let sstate carry
        # that.
        stamp = time.time()
        for near in (os.path.join(root, os.pardir, 'pubspec.yaml'),
                     os.path.join(root, os.pardir, 'pubspec.lock')):
            if os.path.isfile(near):
                os.utime(near, (stamp - 2, stamp - 2))
        os.utime(path, (stamp, stamp))
        graph = os.path.join(root, 'package_graph.json')
        if os.path.isfile(graph):
            os.utime(graph, (stamp, stamp))
}
do_install[postfuncs] += "relativize_dart_package_configs"

python () {
    d.setVar('FLUTTER_SDK_VERSION', get_flutter_sdk_version(d))
}

ALLOW_EMPTY:${PN} = "1"

FILES:${PN} = "${datadir}/flutter/sdk"

INSANE_SKIP:${PN} += "already-stripped file-rdeps libdir"
INSANE_SKIP:${PN}-dbg += "libdir"
INSANE_SKIP:class-nativesdk += "buildpaths"

BBCLASSEXTEND = "native nativesdk"
