# SPDX-FileCopyrightText: (C) 2026 Joel Winarske
# SPDX-License-Identifier: MIT
import hashlib
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))
import pubvendor as p2y  # noqa: E402

MODERN_LOCK = """\
# Generated by pub
packages:
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  my_local:
    dependency: "direct main"
    description:
      path: "../my_local"
      relative: true
    source: path
    version: "1.0.0"
  widgets_a:
    dependency: "direct main"
    description:
      path: "packages/a"
      ref: main
      resolved-ref: "6ca590ceeb9977b727a6b014160b33c0df1e9845"
      url: "https://github.com/example/mono.git"
    source: git
    version: "0.2.0"
  widgets_b:
    dependency: "direct main"
    description:
      path: "packages/b"
      ref: main
      resolved-ref: "6ca590ceeb9977b727a6b014160b33c0df1e9845"
      url: "https://github.com/example/mono.git"
    source: git
    version: "0.3.0"
  scp_dep:
    dependency: "direct main"
    description:
      path: "."
      ref: v1
      resolved-ref: "aabbccddeeff00112233445566778899aabbccdd"
      url: "git@github.com:example/scp_dep.git"
    source: git
    version: "1.0.0"
sdks:
  dart: ">=3.6.0 <4.0.0"
"""

OLD_LOCK = """\
packages:
  args:
    dependency: "direct main"
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
"""


@pytest.fixture
def modern(tmp_path):
    lock = tmp_path / "pubspec.lock"
    lock.write_text(MODERN_LOCK)
    return lock


def test_parse_partitions_sources(modern):
    r = p2y.parse_lockfile(modern)
    assert [h.pkg for h in r.hosted] == ["args"]
    assert len(r.git) == 2  # mono deduped to one clone, scp_dep separate
    assert ("flutter", "sdk") in r.skipped
    assert ("my_local", "path") in r.skipped


def test_lock_sha256_matches_bytes(modern):
    r = p2y.parse_lockfile(modern)
    assert r.lock_sha256 == hashlib.sha256(MODERN_LOCK.encode()).hexdigest()


def test_hosted_entry_deterministic_url_and_checksum(modern):
    r = p2y.parse_lockfile(modern)
    out = r.hosted[0].render(":append", "pub-cache/")
    assert "https://pub.dev/api/archives/args-2.7.0.tar.gz" in out
    assert "subdir=${PUB_CACHE_LOCAL}/hosted/pub.dev/args-2.7.0" in out
    assert "downloadfilename=pub-cache/args-2.7.0.tar.gz" in out
    assert 'SRC_URI[args.sha256sum] = "d0481093' in out[: out.find("sha256sum") + 60]


def test_git_pins_resolved_ref_not_branch_head(modern):
    r = p2y.parse_lockfile(modern)
    mono = next(g for g in r.git if "mono" in g.url)
    assert mono.resolved_ref == "6ca590ceeb9977b727a6b014160b33c0df1e9845"
    out = mono.render(":append")
    assert 'SRCREV_mono = "6ca590ceeb9977b727a6b014160b33c0df1e9845"' in out


def test_git_cache_dir_hashes_raw_url(modern):
    r = p2y.parse_lockfile(modern)
    mono = next(g for g in r.git if "mono" in g.url)
    expect = hashlib.sha1(b"https://github.com/example/mono.git").hexdigest()
    assert f"destsuffix=${{PUB_CACHE_LOCAL}}/git/cache/mono-{expect}" in mono.render(":append")


def test_scp_url_normalized(modern):
    r = p2y.parse_lockfile(modern)
    scp = next(g for g in r.git if g.url.startswith("git@"))
    out = scp.render(":append")
    assert 'git://git@github.com/example/scp_dep.git;name=scp_dep;protocol=ssh' in out
    assert ":example" not in out  # no scp colon leaks into the fetcher URI


def test_normalize_git_url_variants():
    assert p2y.normalize_git_url("https://h/o/r.git") == ("h/o/r.git", "https")
    assert p2y.normalize_git_url("ssh://git@h/o/r.git") == ("git@h/o/r.git", "ssh")
    assert p2y.normalize_git_url("git@h:o/r.git") == ("git@h/o/r.git", "ssh")
    with pytest.raises(ValueError):
        p2y.normalize_git_url("not a url")


def test_ident_collision_disambiguation(tmp_path):
    lock = tmp_path / "pubspec.lock"
    lock.write_text(
        """\
packages:
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: aa
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  args_git:
    dependency: "direct main"
    description:
      path: "."
      ref: main
      resolved-ref: "00112233445566778899aabbccddeeff00112233"
      url: "https://gitlab.com/other/args.git"
    source: git
    version: "9.0.0"
"""
    )
    r = p2y.parse_lockfile(lock)
    idents = {r.hosted[0].ident} | {g.ident for g in r.git}
    assert len(idents) == 2
    assert r.git[0].ident.startswith("args_")  # suffixed, BitBake-safe


def test_render_old_style(modern):
    r = p2y.parse_lockfile(modern)
    text = p2y.render(r, "old", "pub-cache/")
    assert "SRC_URI_append = " in text
    assert "SRC_URI:append" not in text
    assert "SRCREV_FORMAT_append" in text


def test_render_new_style_srcrev_format(modern):
    r = p2y.parse_lockfile(modern)
    text = p2y.render(r, "new", "pub-cache/")
    assert "SRCREV_FORMAT:append" in text
    assert "    mono" in text and "    scp_dep" in text


def test_missing_sha256_is_hard_error_without_flag(tmp_path, capsys):
    lock = tmp_path / "pubspec.lock"
    lock.write_text(OLD_LOCK)
    rc = p2y.main(["-i", str(lock), "-o", str(tmp_path / "out.inc")])
    assert rc == 1
    assert "no lockfile sha256 for: args" in capsys.readouterr().err


def test_main_end_to_end(modern, tmp_path, capsys):
    out = tmp_path / "app.inc"
    rc = p2y.main(["-i", str(modern), "-o", str(out)])
    assert rc == 0
    text = out.read_text()
    assert text.startswith("# Do not edit.")
    assert 'PUBSPEC_LOCK_SHA256 = "' in text
    assert text.count("SRC_URI:append") == 3  # 1 hosted + 2 git
    assert "Skipped (not fetched): flutter (sdk), my_local (path)" in text


def test_output_deterministic(modern, tmp_path):
    a, b = tmp_path / "a.inc", tmp_path / "b.inc"
    p2y.main(["-i", str(modern), "-o", str(a)])
    p2y.main(["-i", str(modern), "-o", str(b)])
    assert a.read_bytes() == b.read_bytes()


def test_encoded_host():
    assert p2y.encoded_host("https://pub.dev") == "pub.dev"
    assert p2y.encoded_host("https://pub.flutter-io.cn/") == "pub.flutter-io.cn"
    assert "%3A" in p2y.encoded_host("https://pub.example.com:8080")
