#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 Joel Winarske
# SPDX-License-Identifier: MIT
#
# pubvendor.py - Generate BitBake SRC_URI fragments from a Dart pubspec.lock
#
# Pure lockfile transform: no network access on the default path. Hosted
# archive URLs are constructed deterministically from the pub API layout
# (<hosted-url>/api/archives/<name>-<version>.tar.gz) and checksums are
# taken from the lockfile `sha256` field (present since Dart 2.19).
# Git SRCREVs are pinned to the lockfile `resolved-ref`.
#
# Lockfiles predating Dart 2.19 lack hosted sha256 fields; pass
# --resolve-missing to fetch each affected archive once at generation
# time and pin the computed digest into the output.
#
# The staged layout replicates the pub cache directory contract:
#   ${PUB_CACHE_LOCAL}/hosted/<encoded-host>/<name>-<version>/   (unpacked)
#   ${PUB_CACHE_LOCAL}/git/cache/<repo>-<sha1(url)>/             (bare clone)
# This contract is a pub internal; it is validated per-SDK by the
# offline `pub get` job in CI, not assumed stable.

import argparse
import hashlib
import re
import sys
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

import yaml

GENERATED_HEADER = """\
# Do not edit. This file is generated by pubvendor.py.
#
# PUB_CACHE_LOCAL is a path relative to ${WORKDIR} specifying the pub
# cache staged by do_unpack. Consume via pub-cache.bbclass, which points
# PUB_CACHE at it and runs `pub get --offline --enforce-lockfile`.
"""

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]")
_SCP_RE = re.compile(r"^(?P<user>[^@/]+@)?(?P<host>[^:/]+):(?P<path>(?!/).+)$")


def sanitize_ident(name: str) -> str:
    """SRC_URI name= / SRCREV_<name> identifier: BitBake-safe subset."""
    return _IDENT_RE.sub("_", name)


def encoded_host(hosted_url: str) -> str:
    """Pub cache hosted directory name for a hosted URL.

    Mirrors pub's urlToDirectory: scheme stripped, remainder
    percent-encoded with '/' mapped to %47. 'https://pub.dev' -> 'pub.dev'.
    Validated against real pub caches by the CI offline-get matrix.
    """
    rest = re.sub(r"^[A-Za-z][A-Za-z0-9+.-]*://", "", hosted_url.rstrip("/"))
    return urllib.parse.quote(rest, safe="").replace("%2F", "%47")


def normalize_git_url(url: str):
    """Return (address, protocol) for the BitBake git fetcher.

    Handles scheme URLs (https://, ssh://, git://) and scp-style
    syntax (git@host:org/repo.git), which the fetcher cannot take
    verbatim because of the colon-delimited path.
    """
    m = re.match(r"^(?P<proto>[A-Za-z][A-Za-z0-9+.-]*)://(?P<addr>.+)$", url)
    if m:
        return m.group("addr"), m.group("proto")
    m = _SCP_RE.match(url)
    if m:
        user = m.group("user") or ""
        return f"{user}{m.group('host')}/{m.group('path')}", "ssh"
    raise ValueError(f"unsupported git URL syntax: {url!r}")


def repo_name(url: str) -> str:
    tail = url.rstrip("/")
    if tail.endswith(".git"):
        tail = tail[:-4]
    return tail.rstrip("/").rsplit("/", 1)[-1] or "repo"


@dataclass
class HostedEntry:
    pkg: str
    version: str
    hosted_url: str
    sha256: str | None
    ident: str = ""

    @property
    def archive_url(self) -> str:
        base = self.hosted_url.rstrip("/")
        return f"{base}/api/archives/{self.pkg}-{self.version}.tar.gz"

    def resolve_sha256(self) -> None:
        with urllib.request.urlopen(self.archive_url) as rsp:  # noqa: S310
            self.sha256 = hashlib.sha256(rsp.read()).hexdigest()

    def render(self, op: str, download_prefix: str) -> str:
        subdir = (
            f"${{PUB_CACHE_LOCAL}}/hosted/"
            f"{encoded_host(self.hosted_url)}/{self.pkg}-{self.version}"
        )
        dlname = f"{download_prefix}{self.pkg}-{self.version}.tar.gz"
        return (
            f'SRC_URI{op} = " {self.archive_url};name={self.ident};'
            f'subdir={subdir};downloadfilename={dlname}"\n'
            f'SRC_URI[{self.ident}.sha256sum] = "{self.sha256}"\n'
        )


@dataclass
class GitEntry:
    pkg: str
    url: str
    resolved_ref: str
    ident: str = ""

    @property
    def url_sha1(self) -> str:
        # pub keys its git cache dir on sha1 of the URL as written in
        # the lockfile -- hash the raw string, no canonicalization.
        return hashlib.sha1(self.url.encode()).hexdigest()  # noqa: S324

    def render(self, op: str) -> str:
        address, protocol = normalize_git_url(self.url)
        cache_dir = f"{repo_name(self.url)}-{self.url_sha1}"
        return (
            f'SRC_URI{op} = " git://{address};name={self.ident};'
            f"protocol={protocol};"
            f"destsuffix=${{PUB_CACHE_LOCAL}}/git/cache/{cache_dir};"
            f'nobranch=1;bareclone=1"\n'
            f'SRCREV_{self.ident} = "{self.resolved_ref}"\n'
        )


@dataclass
class LockfileRecipe:
    hosted: list[HostedEntry] = field(default_factory=list)
    git: list[GitEntry] = field(default_factory=list)
    skipped: list[tuple[str, str]] = field(default_factory=list)  # (pkg, source)
    lock_sha256: str = ""


def parse_lockfile(path: Path) -> LockfileRecipe:
    data = path.read_bytes()
    doc = yaml.safe_load(data)
    if not isinstance(doc, dict) or "packages" not in doc:
        raise ValueError(f"{path}: not a pubspec.lock (missing 'packages')")

    out = LockfileRecipe(lock_sha256=hashlib.sha256(data).hexdigest())
    seen_git_urls: set[str] = set()

    for pkg, meta in sorted(doc["packages"].items()):
        source = meta.get("source")
        desc = meta.get("description")
        if source == "hosted":
            if not isinstance(desc, dict) or "url" not in desc:
                raise ValueError(f"{pkg}: hosted entry missing description.url")
            out.hosted.append(
                HostedEntry(
                    pkg=pkg,
                    version=str(meta["version"]),
                    hosted_url=desc["url"],
                    sha256=desc.get("sha256"),
                )
            )
        elif source == "git":
            if not isinstance(desc, dict):
                raise ValueError(f"{pkg}: git entry missing description map")
            url, ref = desc.get("url"), desc.get("resolved-ref")
            if not url or not ref:
                raise ValueError(f"{pkg}: git entry missing url/resolved-ref")
            if url in seen_git_urls:
                continue  # one bare clone per repo serves all its packages
            seen_git_urls.add(url)
            out.git.append(GitEntry(pkg=pkg, url=url, resolved_ref=ref))
        else:
            # sdk: provided by the toolchain; path: in-tree with the app
            out.skipped.append((pkg, str(source)))

    _assign_idents(out)
    return out


def _assign_idents(recipe: LockfileRecipe) -> None:
    """Unique BitBake-safe name= identifiers across hosted and git entries.

    Hosted package names are unique within a lockfile; git repo basenames
    can collide with each other and with hosted names, so disambiguate
    with a short URL-hash suffix.
    """
    taken: set[str] = set()
    for h in recipe.hosted:
        h.ident = sanitize_ident(h.pkg)
        taken.add(h.ident)
    for g in recipe.git:
        base = sanitize_ident(repo_name(g.url))
        g.ident = base if base not in taken else f"{base}_{g.url_sha1[:7]}"
        taken.add(g.ident)


def render(recipe: LockfileRecipe, style: str, download_prefix: str,
           provenance: str = "") -> str:
    op = ":append" if style == "new" else "_append"
    parts = [GENERATED_HEADER]
    if provenance:
        # Whose resolution this is. A reader of the fragment cannot otherwise
        # tell the app's own lockfile from one the roll produced, and the two
        # mean different things: the first is what upstream tested, the second
        # is what this layer settled on because the first did not hold.
        parts.append(f"#\n# Lockfile: {provenance}\n")
    parts.append("\n")
    parts.append('PUB_CACHE_LOCAL ?= "pub_cache"\n')
    parts.append(f'PUBSPEC_LOCK_SHA256 = "{recipe.lock_sha256}"\n\n')

    parts.append("# Hosted packages\n")
    for h in recipe.hosted:
        parts.append(h.render(op, download_prefix))
    if recipe.git:
        parts.append("\n# Git packages\n")
        for g in recipe.git:
            parts.append(g.render(op))
        names = " \\\n".join(f"    {g.ident}" for g in recipe.git)
        parts.append(f'\nSRCREV_FORMAT{op} = " \\\n{names} \\\n"\n')
    if recipe.skipped:
        skipped = ", ".join(f"{p} ({s})" for p, s in recipe.skipped)
        parts.append(f"\n# Skipped (not fetched): {skipped}\n")
    return "".join(parts)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate a BitBake .inc staging the pub cache from pubspec.lock"
    )
    ap.add_argument("-i", "--lockfile", type=Path, default=Path("pubspec.lock"))
    ap.add_argument(
        "-o", "--output", type=Path, default=None,
        help="output path (default: <project>.inc beside the lockfile)",
    )
    ap.add_argument(
        "--style", choices=("new", "old"), default="new",
        help="override syntax: 'new' = :append (kirkstone+), 'old' = _append",
    )
    ap.add_argument(
        "--download-prefix", default="pub-cache/",
        help="DL_DIR subdirectory prefix for hosted tarballs",
    )
    ap.add_argument(
        "--provenance", default="",
        help="one line recorded in the fragment header saying where the "
             "lockfile came from",
    )
    ap.add_argument(
        "--resolve-missing", action="store_true",
        help="fetch archives lacking a lockfile sha256 (pre-Dart-2.19 "
             "lockfiles) and pin the computed digest",
    )
    args = ap.parse_args(argv)

    if not args.lockfile.is_file():
        print(f"error: {args.lockfile}: no such file", file=sys.stderr)
        return 1

    try:
        recipe = parse_lockfile(args.lockfile)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    missing = [h for h in recipe.hosted if not h.sha256]
    if missing:
        if not args.resolve_missing:
            names = ", ".join(h.pkg for h in missing)
            print(
                f"error: no lockfile sha256 for: {names}\n"
                "  (pre-Dart-2.19 lockfile; regenerate with a newer SDK "
                "or pass --resolve-missing)",
                file=sys.stderr,
            )
            return 1
        for h in missing:
            print(f"resolving sha256: {h.pkg}-{h.version}", file=sys.stderr)
            h.resolve_sha256()

    out = args.output
    if out is None:
        project = _project_name(args.lockfile.parent / "pubspec.yaml")
        out = args.lockfile.parent / f"{project}.inc"

    out.write_text(render(recipe, args.style, args.download_prefix,
                          args.provenance))
    print(
        f"{out}: {len(recipe.hosted)} hosted, {len(recipe.git)} git, "
        f"{len(recipe.skipped)} skipped",
        file=sys.stderr,
    )
    return 0


def _project_name(pubspec: Path) -> str:
    if pubspec.is_file():
        doc = yaml.safe_load(pubspec.read_text())
        if isinstance(doc, dict) and isinstance(doc.get("name"), str):
            return doc["name"]
    return "pubspec"


if __name__ == "__main__":
    sys.exit(main())
