# SPDX-License-Identifier: MIT
"""The roll must not conflate creating a lockfile with replacing one.

An app that ships no pubspec.lock has nothing to preserve. An app that ships
one has an author's resolution, possibly with pins that matter. Deleting
unconditionally treated both the same and said nothing about which had
happened. See #861.
"""
import os
import stat
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import create_recipes  # noqa: E402

LOCK = """\
# Generated by pub
packages:
  args:
    dependency: "direct main"
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
sdks:
  dart: ">=3.6.0 <4.0.0"
"""


@pytest.fixture
def app(tmp_path, monkeypatch):
    """An app dir, an output dir, and a `flutter` on PATH we control."""
    app_dir = tmp_path / 'app'
    app_dir.mkdir()
    (app_dir / 'pubspec.yaml').write_text('name: probe\n')
    out = tmp_path / 'out'
    out.mkdir()

    bin_dir = tmp_path / 'bin'
    bin_dir.mkdir()
    shim = bin_dir / 'flutter'
    # Writes a lockfile on a plain `pub get`; honours ENFORCE_RC so a test can
    # say whether the committed lockfile still holds.
    shim.write_text(
        '#!/bin/sh\n'
        'case "$*" in\n'
        '  *--enforce-lockfile*) exit "${ENFORCE_RC:-0}" ;;\n'
        'esac\n'
        f'cat > pubspec.lock <<\'EOF\'\n{LOCK}EOF\n'
        'echo resolved > resolved.marker\n'
    )
    shim.chmod(shim.stat().st_mode | stat.S_IEXEC)
    monkeypatch.setenv('PATH', str(bin_dir), prepend=os.pathsep)
    return app_dir, out


def _header(out, name='probe'):
    return (out / f'{name}-pubcache.inc').read_text()


def test_no_lockfile_is_created_not_replaced(app):
    app_dir, out = app
    assert create_recipes.generate_pubcache_inc(str(app_dir), 'probe', str(out))
    assert 'Lockfile: created by the roll; none is shipped' in _header(out)


def test_a_holding_lockfile_is_kept(app, monkeypatch):
    app_dir, out = app
    (app_dir / 'pubspec.lock').write_text(LOCK)
    monkeypatch.setenv('ENFORCE_RC', '0')
    assert create_recipes.generate_pubcache_inc(str(app_dir), 'probe', str(out))
    assert "Lockfile: the project's own, unchanged" in _header(out)
    # the author's resolution was never re-run
    assert not (app_dir / 'resolved.marker').exists()


def test_a_lockfile_that_does_not_hold_is_re_resolved(app, monkeypatch):
    app_dir, out = app
    (app_dir / 'pubspec.lock').write_text('packages: {}\n')
    monkeypatch.setenv('ENFORCE_RC', '1')
    assert create_recipes.generate_pubcache_inc(str(app_dir), 'probe', str(out))
    assert "did not hold" in _header(out)
    assert (app_dir / 'resolved.marker').exists()


def test_resolve_override_replaces_a_holding_lockfile(app, monkeypatch):
    app_dir, out = app
    (app_dir / 'pubspec.lock').write_text(LOCK)
    monkeypatch.setenv('ENFORCE_RC', '0')   # it would have held
    assert create_recipes.generate_pubcache_inc(str(app_dir), 'probe', str(out),
                                                always_resolve=True)
    assert 'pubvendor: resolve' in _header(out)
    assert (app_dir / 'resolved.marker').exists()


def test_the_lockfile_is_shipped_beside_the_fragment(app):
    app_dir, out = app
    assert create_recipes.generate_pubcache_inc(str(app_dir), 'probe', str(out))
    shipped = out / 'probe-pubspec.lock'
    assert shipped.exists()
    assert shipped.read_text() == (app_dir / 'pubspec.lock').read_text()


def test_vendor_only_leaves_the_recipe_alone(app, monkeypatch, tmp_path):
    """An app whose recipe is hand-written but whose cache the roll maintains.

    The generator only ever emits `inherit flutter-app`, so generating over a
    recipe that inherits flutter-app-native, or carries extra tasks, silently
    drops whatever made it work. generate_recipes=False vendors the cache and
    writes no recipe. See #888.
    """
    import create_recipes
    app_dir, out = app
    (app_dir / 'pubspec.yaml').write_text('name: probe\nversion: 1.0.0\n')

    result = create_recipes.create_recipe(
        directory=str(app_dir.parent),
        pubspec_yaml=str(app_dir / 'pubspec.yaml'),
        flutter_application_path='app',
        org='o', unit='u', submodules=False,
        url='https://example.invalid/x.git', lfs=False, branch='main',
        commit='deadbeef',
        license_file=None, license_type='CLOSED', license_md5='',
        author='x', recipe_folder='third-party', output_path=str(out),
        rdepends_list=None, output_path_override_list=None,
        compiler_requires_network_list=None, src_folder=None, src_files=None,
        variables=None, patch_dir=None, pubvendor=True,
        generate_recipes=False)

    assert result == ''
    assert not list(out.rglob('*.bb')), 'a recipe was written despite generate_recipes=False'
    assert list(out.rglob('*-pubcache.inc')), 'the fragment was not vendored'
    assert list(out.rglob('*-pubspec.lock')), 'the lockfile was not shipped'
