#
# Copyright (c) 2020-2024 Joel Winarske. All rights reserved.
#

# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes*/*/*.bb \
    ${LAYERDIR}/recipes*/*/*.bbappend \
    ${LAYERDIR}/recipes*/*/*/*.bb \
    ${LAYERDIR}/recipes*/*/*/*.bbappend \
    ${LAYERDIR}/images/*.bb \
"

BBFILE_COLLECTIONS += "flutter-layer"
BBFILE_PATTERN_flutter-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_flutter-layer = "12"

LAYERDEPENDS_flutter-layer = "core openembedded-layer"
LAYERSERIES_COMPAT_flutter-layer = "whinlatter wrynose"

# Sony flutter-embedded-linux recipes deprecated. flutter-elinux recipes used by default.
# Set FLUTTER_ELINUX_USE_SONY = "1" to use the deprecated sony recipes instead.
BBMASK += "${@'/recipes-graphics/flutter-elinux/' if d.getVar('FLUTTER_ELINUX_USE_SONY') == '1' else '/recipes-graphics/sony/'}"

addpylib ${LAYERDIR}/lib gn
addpylib ${LAYERDIR}/lib cipd
