name: kirkstone-linux-dummy

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  linux-dummy:
  
    env:
      YOCTO_VERSION: 4.0
      YOCTO_BRANCH: kirkstone
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/kirkstone/latest:/home/dev/sstate:Z

    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../yocto-kirkstone ] || mkdir -p ../yocto-kirkstone
          cd ../yocto-kirkstone
          pwd
          ls -la
          rm -rf poky meta-openembedded meta-clang
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.yoctoproject.org/poky &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.openembedded.org/meta-openembedded &
          git clone -b ${{ env.YOCTO_BRANCH }}-clang12 --single-branch https://github.com/kraj/meta-clang.git &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          rm -rf build/conf
          . ./poky/oe-init-build-env
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.YOCTO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'INIT_MANAGER = "systemd"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES:remove = "sysvinit"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES:append = " x11 wayland opengl"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_BACKFILL_CONSIDERED = ""' >> ./conf/local.conf
          echo 'INHIBIT_PACKAGE_DEBUG_SPLIT = "1"' >> ./conf/local.conf
          echo 'PREFERRED_PROVIDER:virtual/kernel = "linux-dummy"' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_ACCEPTED = "commercial"' >> ./conf/local.conf
          echo 'IMAGE_INSTALL:append = " \
              gstreamer1.0 \
              gstreamer1.0-libav \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              ffmpeg \
              "' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers add-layer \
              ../meta-openembedded/meta-oe \
              ../meta-openembedded/meta-python \
              ../meta-openembedded/meta-networking \
              ../meta-clang \
              ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake ca-certificates -c do_cleansstate
          bitbake ca-certificates-native -c do_cleansstate
          bitbake flutter-sdk-native -c do_cleansstate

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake core-image-minimal

      - name: Build membrane-dart-example
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake membrane-dart-example -c do_cleansstate
          bitbake membrane-dart-example

      - name: Build agl-flutter-igalia-homescreen
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake agl-flutter-igalia-homescreen-runtimedebug -c do_cleansstate
          bitbake agl-flutter-igalia-homescreen-runtimeprofile -c do_cleansstate
          bitbake agl-flutter-igalia-homescreen-runtimerelease -c do_cleansstate
          bitbake agl-flutter-igalia-homescreen-runtimedebug
          bitbake agl-flutter-igalia-homescreen-runtimeprofile
          bitbake agl-flutter-igalia-homescreen-runtimerelease

      - name: Build agl-flutter-pumped-fuel-ped
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake agl-flutter-pumped-fuel-ped-runtimedebug -c do_cleansstate
          bitbake agl-flutter-pumped-fuel-ped-runtimeprofile -c do_cleansstate
          bitbake agl-flutter-pumped-fuel-ped-runtimerelease -c do_cleansstate
          bitbake agl-flutter-pumped-fuel-ped-runtimedebug
          bitbake agl-flutter-pumped-fuel-ped-runtimeprofile
          bitbake agl-flutter-pumped-fuel-ped-runtimerelease

      - name: Build flutter-engine
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-engine-runtimerelease -c do_cleansstate
          bitbake flutter-engine-runtimeprofile -c do_cleansstate
          bitbake flutter-engine-runtimedebug -c do_cleansstate
          bitbake flutter-engine-runtimerelease
          bitbake flutter-engine-runtimeprofile
          bitbake flutter-engine-runtimedebug

      - name: Build flutter-pi
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-pi-runtimerelease -c do_cleansstate
          bitbake flutter-pi-runtimeprofile -c do_cleansstate
          bitbake flutter-pi-runtimedebug -c do_cleansstate
          bitbake flutter-pi-runtimerelease
          bitbake flutter-pi-runtimeprofile
          bitbake flutter-pi-runtimedebug

      - name: Build ivi-homescreen
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake ivi-homescreen-runtimerelease -c do_cleansstate
          bitbake ivi-homescreen-runtimeprofile -c do_cleansstate
          bitbake ivi-homescreen-runtimedebug -c do_cleansstate
          bitbake ivi-homescreen-runtimerelease
          bitbake ivi-homescreen-runtimeprofile
          bitbake ivi-homescreen-runtimedebug

      - name: Build flutter-drm-eglstream-backend
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-drm-eglstream-backend-runtimerelease -c do_cleansstate
          bitbake flutter-drm-eglstream-backend-runtimeprofile -c do_cleansstate
          bitbake flutter-drm-eglstream-backend-runtimedebug -c do_cleansstate
          bitbake flutter-drm-eglstream-backend-runtimerelease
          bitbake flutter-drm-eglstream-backend-runtimeprofile
          bitbake flutter-drm-eglstream-backend-runtimedebug

      - name: Build drm gbm backend
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-drm-gbm-backend-runtimerelease -c do_cleansstate
          bitbake flutter-drm-gbm-backend-runtimeprofile -c do_cleansstate
          bitbake flutter-drm-gbm-backend-runtimedebug -c do_cleansstate
          bitbake flutter-drm-gbm-backend-runtimerelease
          bitbake flutter-drm-gbm-backend-runtimeprofile
          bitbake flutter-drm-gbm-backend-runtimedebug

      - name: Build external texture plugin
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-external-texture-plugin-runtimerelease -c do_cleansstate
          bitbake flutter-external-texture-plugin-runtimeprofile -c do_cleansstate
          bitbake flutter-external-texture-plugin-runtimedebug -c do_cleansstate
          bitbake flutter-external-texture-plugin-runtimerelease
          bitbake flutter-external-texture-plugin-runtimeprofile
          bitbake flutter-external-texture-plugin-runtimedebug

      - name: Build video player plugin
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-video-player-plugin-runtimerelease -c do_cleansstate
          bitbake flutter-video-player-plugin-runtimeprofile -c do_cleansstate
          bitbake flutter-video-player-plugin-runtimedebug -c do_cleansstate
          bitbake flutter-video-player-plugin-runtimerelease
          bitbake flutter-video-player-plugin-runtimeprofile
          bitbake flutter-video-player-plugin-runtimedebug

      - name: Build Wayland Client
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-wayland-client-runtimerelease -c do_cleansstate
          bitbake flutter-wayland-client-runtimeprofile -c do_cleansstate
          bitbake flutter-wayland-client-runtimedebug -c do_cleansstate
          bitbake flutter-wayland-client-runtimerelease
          bitbake flutter-wayland-client-runtimeprofile
          bitbake flutter-wayland-client-runtimedebug

      - name: Build X11 Client
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-x11-client-runtimerelease -c do_cleansstate
          bitbake flutter-x11-client-runtimeprofile -c do_cleansstate
          bitbake flutter-x11-client-runtimedebug -c do_cleansstate
          bitbake flutter-x11-client-runtimerelease
          bitbake flutter-x11-client-runtimeprofile
          bitbake flutter-x11-client-runtimedebug

      - name: Build flutter-gallery
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-gallery-runtimerelease -c do_cleansstate
          bitbake flutter-gallery-runtimeprofile -c do_cleansstate
          bitbake flutter-gallery-runtimedebug -c do_cleansstate
          bitbake flutter-gallery-runtimerelease
          bitbake flutter-gallery-runtimeprofile
          bitbake flutter-gallery-runtimedebug

      - name: Build flutter-test-plugins
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-test-plugins-runtimerelease -c do_cleansstate
          bitbake flutter-test-plugins-runtimeprofile -c do_cleansstate
          bitbake flutter-test-plugins-runtimedebug -c do_cleansstate
          bitbake flutter-test-plugins-runtimerelease
          bitbake flutter-test-plugins-runtimeprofile
          bitbake flutter-test-plugins-runtimedebug

      - name: Build flutter-test-secure-storage
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-test-secure-storage-runtimerelease -c do_cleansstate
          bitbake flutter-test-secure-storage-runtimeprofile -c do_cleansstate
          bitbake flutter-test-secure-storage-runtimedebug -c do_cleansstate
          bitbake flutter-test-secure-storage-runtimerelease
          bitbake flutter-test-secure-storage-runtimeprofile
          bitbake flutter-test-secure-storage-runtimedebug

      - name: Build flutter-test-texture-egl
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-test-texture-egl-runtimerelease -c do_cleansstate
          bitbake flutter-test-texture-egl-runtimeprofile -c do_cleansstate
          bitbake flutter-test-texture-egl-runtimedebug -c do_cleansstate
          bitbake flutter-test-texture-egl-runtimerelease
          bitbake flutter-test-texture-egl-runtimeprofile
          bitbake flutter-test-texture-egl-runtimedebug

      - name: Build flutter-test-video-player
        shell: bash
        working-directory: ../yocto-kirkstone
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-test-video-player-runtimerelease -c do_cleansstate
          bitbake flutter-test-video-player-runtimeprofile -c do_cleansstate
          bitbake flutter-test-video-player-runtimedebug -c do_cleansstate
          bitbake flutter-test-video-player-runtimerelease
          bitbake flutter-test-video-player-runtimeprofile
          bitbake flutter-test-video-player-runtimedebug
