#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#

SUMMARY = "Dart executable with a pub dependency, built for the target"
DESCRIPTION = "Proves dart-app-pub: the app's pub dependencies arrive through \
SRC_URI with checksums, pub resolves against the staged cache with the network \
off, and the result is cross-compiled to an AOT snapshot. See meta-flutter#428."
AUTHOR = "Joel Winarske"
SECTION = "devtools"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

SRC_URI = " \
    file://pubspec.yaml \
    file://bin/main.dart \
    file://dart-example-pub-pubspec.lock \
    "

# The vendored cache, generated by tools/pubvendor from the lockfile above.
require dart-example-pub-pubcache.inc

# pub-cache installs this over the app's own lockfile before resolving, so
# what gets built is what was vendored.
PUBSPEC_LOCK_FILE = "dart-example-pub-pubspec.lock"

S = "${UNPACKDIR}"
PUBSPEC_APP_DIR = "${S}"

inherit dart-app-pub
