#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "data_asset_app"
DESCRIPTION = "A new Flutter project."

PUBSPEC_APPNAME = "data_asset_app"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/data_asset_app"

require conf/include/flutter-sdk-app.inc
