#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "integration_ui"
DESCRIPTION = "Flutter non-plugin UI integration tests."

PUBSPEC_APPNAME = "integration_ui"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/ui"

require conf/include/flutter-sdk-app.inc
