#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "flavors"
DESCRIPTION = "Integration test for build flavors."

PUBSPEC_APPNAME = "flavors"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/flavors"

require conf/include/flutter-sdk-app.inc
