#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "flutter_gallery"
DESCRIPTION = "The Flutter gallery: material and cupertino demos, the SDK's largest example app and the first with dependencies that resolve to something."

PUBSPEC_APPNAME = "flutter_gallery"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/flutter_gallery"

RDEPENDS:${PN} += "xdg-user-dirs"

require conf/include/flutter-sdk-app.inc
