#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "multiple_windows"
DESCRIPTION = "The Flutter SDK's multiple_windows example application."

PUBSPEC_APPNAME = "multiple_windows"
FLUTTER_APPLICATION_PATH = "examples/multiple_windows"

require conf/include/flutter-sdk-app.inc
