#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "texture"
DESCRIPTION = "The Flutter SDK's texture example application."

PUBSPEC_APPNAME = "texture"
FLUTTER_APPLICATION_PATH = "examples/texture"

require conf/include/flutter-sdk-app.inc
