#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "windowing_test"
DESCRIPTION = "Flutter windowing integration tests."

PUBSPEC_APPNAME = "windowing_test"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/windowing_test"

require conf/include/flutter-sdk-app.inc
