#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "platform_channel"
DESCRIPTION = "The Flutter SDK's platform_channel example application."

PUBSPEC_APPNAME = "platform_channel"
FLUTTER_APPLICATION_PATH = "examples/platform_channel"

require conf/include/flutter-sdk-app.inc
