#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "a11y_assessments"
DESCRIPTION = "A new Flutter project"

PUBSPEC_APPNAME = "a11y_assessments"
FLUTTER_APPLICATION_PATH = "dev/a11y_assessments"

require conf/include/flutter-sdk-app.inc
