#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "record_use_test_app"
DESCRIPTION = "A new Flutter application project."

PUBSPEC_APPNAME = "record_use_test_app"
FLUTTER_APPLICATION_PATH = "dev/integration_tests/record_use_test_app"

require conf/include/flutter-sdk-app.inc
