#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "manual_tests"
DESCRIPTION = "The Flutter SDK's manual_tests example application."

PUBSPEC_APPNAME = "manual_tests"
FLUTTER_APPLICATION_PATH = "dev/manual_tests"

require conf/include/flutter-sdk-app.inc
