#
# Copyright (c) 2026 Joel Winarske
#
# SPDX-License-Identifier: MIT
#
# Generated by tools/sdk_apps.py. Edit the overrides file, not this.
#

SUMMARY = "flutter_examples_layers"
DESCRIPTION = "The Flutter SDK's flutter_examples_layers example application."

PUBSPEC_APPNAME = "flutter_examples_layers"
FLUTTER_APPLICATION_PATH = "examples/layers"

require conf/include/flutter-sdk-app.inc
