name: dunfell-linux-dummy

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  linux-dummy:
  
    env:
      YOCTO_VERSION: 3.1.13
      YOCTO_BRANCH: dunfell
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/dunfell/latest:/home/dev/sstate:Z

    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u

      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2

      - name: Fetch poky
        run: |
          [ -d ../yocto-dunfell ] || mkdir -p ../yocto-dunfell
          cd ../yocto-dunfell
          pwd
          ls -la
          rm -rf poky meta-openembedded meta-clang
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.yoctoproject.org/poky &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.openembedded.org/meta-openembedded &
          git clone -b dunfell-clang12 --single-branch https://github.com/kraj/meta-clang.git &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          rm -rf build/conf
          . ./poky/oe-init-build-env
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.YOCTO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'INIT_MANAGER = "systemd"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_remove = " sysvinit"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES += "x11 wayland opengl vulkan"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_BACKFILL_CONSIDERED = ""' >> ./conf/local.conf
          echo 'INHIBIT_PACKAGE_DEBUG_SPLIT = "1"' >> ./conf/local.conf
          echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_WHITELIST += "commercial"' >> ./conf/local.conf
          echo 'PACKAGECONFIG_append_pn-flutter-engine-runtimedebug = " desktop-embeddings"' >> conf/local.conf
          echo 'PACKAGECONFIG_append_pn-flutter-engine-runtimeprofile = " desktop-embeddings"' >> conf/local.conf
          echo 'PACKAGECONFIG_append_pn-flutter-engine-runtimerelease = " desktop-embeddings"' >> conf/local.conf
          echo 'IMAGE_INSTALL_append = " \
              gstreamer1.0 \
              gstreamer1.0-libav \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              ffmpeg \
              "' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers add-layer \
              ../meta-openembedded/meta-oe \
              ../meta-openembedded/meta-python \
              ../meta-openembedded/meta-networking \
              ../meta-clang \
              ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake ca-certificates -c do_cleansstate
          bitbake ca-certificates-native -c do_cleansstate
          bitbake flutter-sdk-native -c do_cleansstate

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake core-image-minimal

      - name: Build flutter-engine-runtimerelease
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-engine-runtimerelease -c do_cleansstate
          bitbake flutter-engine-runtimerelease

      - name: Build flutter-gallery-runtimerelease
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-gallery-runtimerelease -c do_cleansstate
          bitbake flutter-gallery-runtimerelease

      - name: Build flutter-engine-runtimeprofile
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-engine-runtimeprofile -c do_cleansstate
          bitbake flutter-engine-runtimeprofile

      - name: Build flutter-gallery-runtimeprofile
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-gallery-runtimeprofile -c do_cleansstate
          bitbake flutter-gallery-runtimeprofile

      - name: Build flutter-auto-runtimerelease
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-auto-runtimerelease -c do_cleansstate
          bitbake flutter-auto-runtimerelease

      - name: Build flutter-auto-runtimeprofile
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-auto-runtimeprofile -c do_cleansstate
          bitbake flutter-auto-runtimeprofile

      - name: Build flutter-auto-runtimedebug
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-auto-runtimedebug -c do_cleansstate
          bitbake flutter-auto-runtimedebug

      - name: Build flutter-pi-runtimerelease
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-pi-runtimerelease -c do_cleansstate
          bitbake flutter-pi-runtimerelease

      - name: Build flutter-pi-runtimeprofile
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-pi-runtimeprofile -c do_cleansstate
          bitbake flutter-pi-runtimeprofile

      - name: Build flutter-pi-runtimedebug
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-pi-runtimedebug -c do_cleansstate
          bitbake flutter-pi-runtimedebug

      - name: Build flutter-drm-eglstream-backend
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-drm-eglstream-backend -c do_cleansstate
          bitbake flutter-drm-eglstream-backend

      - name: Build drm gbm backend
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-drm-gbm-backend -c do_cleansstate
          bitbake flutter-drm-gbm-backend

      - name: Build external texture plugin
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-external-texture-plugin -c do_cleansstate
          bitbake flutter-external-texture-plugin

      - name: Build video player plugin
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-video-player-plugin -c do_cleansstate
          bitbake flutter-video-player-plugin

      - name: Build Wayland Client
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-wayland-client -c do_cleansstate
          bitbake flutter-wayland-client

      - name: Build X11 Client
        shell: bash
        working-directory: ../yocto-dunfell
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-x11-client -c do_cleansstate
          bitbake flutter-x11-client
