name: dunfell-qemuarm-linux-dummy

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]

jobs:

  dunfell-qemuarm-linux-dummy:

    env:
      MACHINE: qemuarm
      YOCTO_BRANCH: dunfell

    runs-on: [self-hosted, linux]

    container:
      image: ghcr.io/meta-flutter/meta-flutter/ubuntu-22-dev:main
      options:
        --read-only
        --log-driver=none
        --user 1001:1001
        --userns keep-id:uid=1001,gid=1001
        --security-opt label=disable
        --pids-limit=-1
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /home/runner/.ssh:/home/dev/.ssh:ro
        -v /mnt/raid10/github-ci/download:/home/dev/dl:Z
        -v /mnt/raid10/github-ci/sstate/yocto/dunfell-linux-dummy:/home/dev/sstate:Z


    steps:

      - uses: actions/checkout@v4
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../dunfell-linux-dummy ] || mkdir -p ../dunfell-linux-dummy
          cd ../dunfell-linux-dummy
          pwd
          ls -la
          rm -rf poky meta-openembedded meta-clang meta-vulkan
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.yoctoproject.org/poky &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch git://git.openembedded.org/meta-openembedded &
          git clone -b ${{ env.YOCTO_BRANCH }} --single-branch https://github.com/jwinarske/meta-vulkan.git &
          git clone -b dunfell-clang14 --single-branch https://github.com/kraj/meta-clang.git meta-clang &
          wait

      - name: Configure build
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          rm -rf build/conf
          . ./poky/oe-init-build-env
          echo '***************************************'
          echo 'INHERIT += "rm_work"' >> ./conf/local.conf
          echo 'INHIBIT_PACKAGE_DEBUG_SPLIT = "1"' >> ./conf/local.conf
          echo '***************************************'
          sed -i '/MACHINE ??=/d' ./conf/local.conf
          echo "MACHINE ??= \"${{ env.MACHINE }}\"" >> ./conf/local.conf
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'BB_SIGNATURE_HANDLER = "OEEquivHash"' >> ./conf/local.conf
          echo 'BB_HASHSERVE = "auto"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS ?= "file://.* https://sstate.yoctoproject.org/all/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'INIT_MANAGER = "systemd"' >> ./conf/local.conf
          echo '***************************************'
          echo 'DISTRO_FEATURES:remove = "sysvinit ptest x11"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES:append = " systemd wayland opengl polkit"' >> ./conf/local.conf
          echo 'DISTRO_FEATURES_BACKFILL_CONSIDERED = ""' >> ./conf/local.conf
          echo 'PREFERRED_PROVIDER_virtual/kernel = "linux-dummy"' >> ./conf/local.conf
          echo 'LICENSE_FLAGS_WHITELIST += "commercial"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-ffmpeg = " openssl"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-flutter-auto = " filament-view"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:append:pn-ivi-homescreen = " filament-view"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:remove:pn-flutter-engine = " debug profile"' >> ./conf/local.conf
          echo '***************************************'
          echo 'IMAGE_INSTALL:append = " \
              gstreamer1.0 \
              gstreamer1.0-libav \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-base \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              ffmpeg \
              "' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers show-layers
          bitbake-layers add-layer \
              ../meta-clang \
              ../meta-openembedded/meta-filesystems \
              ../meta-openembedded/meta-gnome \
              ../meta-openembedded/meta-multimedia \
              ../meta-openembedded/meta-networking \
              ../meta-openembedded/meta-oe \
              ../meta-openembedded/meta-python \
              ../meta-vulkan \
              ../../meta-flutter \
              ../../meta-flutter/meta-flutter-apps
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment
          bitbake ca-certificates -c do_cleansstate
          bitbake ca-certificates-native -c do_cleansstate
          bitbake flutter-sdk-native -c do_cleansstate

      - name: Build dart-sdk
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake dart-sdk -c do_cleansstate
          bitbake dart-sdk

      - name: Build flutter-engine
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-engine -c do_cleansstate
          bitbake flutter-engine

      - name: Build ivi-homescreen
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake ivi-homescreen -c do_cleansstate
          bitbake ivi-homescreen

      - name: Build flutter-auto
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-auto -c do_cleansstate
          bitbake flutter-auto

      - name: Build flutter-pi
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-pi -c do_cleansstate
          bitbake flutter-pi

      - name: Build Sony external texture plugin
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-external-texture-plugin -c do_cleansstate
          bitbake flutter-external-texture-plugin

      - name: Build Sony video player plugin
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-video-player-plugin -c do_cleansstate
          bitbake flutter-video-player-plugin

      - name: Build Sony Wayland Client
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-wayland-client -c do_cleansstate
          bitbake flutter-wayland-client

      - name: Build flutter-samples-material-3-demo
        shell: bash
        working-directory: ../dunfell-linux-dummy
        run: |
          . ./poky/oe-init-build-env
          bitbake flutter-samples-material-3-demo -c do_cleansstate
          bitbake flutter-samples-material-3-demo
