name: honister-rpi3-32

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  honister-rpi3-drm:
  
    env:
      DISTRO_VERSION: 3.4
      YOCTO_BRANCH: honister
      MACHINE: raspberrypi3
      
    runs-on: [self-hosted, linux]
    
    container:
      image: ghcr.io/meta-flutter/ubuntu-20-dev:main
      options:
        --user 1018
        --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs
        --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1
        -v /b/github-ci/download:/home/dev/dl:Z
        -v /b/github-ci/sstate/yocto/honister/rpi3-32-drm/latest:/home/dev/sstate:Z
        -v /b/github-ci/artifacts/rpi3-32/drm:/home/dev/artifacts:Z


    steps:
    
      - name: Display UID Info
        run: |
          whoami
          id -u
          
      - name: Set Ownership
        run: |
          chown -R dev:dev $HOME .
          
      - uses: actions/checkout@v2
        with:
          path: ''

      - name: Fetch poky
        run: |
          [ -d ../rpi3-32-drm-honister-latest ] || mkdir -p ../rpi3-32-drm-honister-latest
          cd ../rpi3-32-drm-honister-latest
          rm -rf sources || true
          ls -la
          git config --list
          git config --global user.email joel@winarske@gmail.com
          git config --global user.name "Joel Winarske"
          git config --list
          /home/dev/bin/repo init -u https://github.com/jwinarske/manifests.git -m rpi64.xml -b $YOCTO_BRANCH
          /home/dev/bin/repo sync --force-sync --no-clone-bundle -j `grep -c ^processor /proc/cpuinfo` &
          wait
          cd sources/poky
          git reset --hard
          git checkout honister
          git checkout honister-3.4
          git apply ../../conf/rpi64/0001-vulkan-loader-pc-prefix-fix.patch
          cd ../..

      - name: Configure build
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          rm -rf ${{ env.MACHINE }}/conf || true
          . ./setup-environment ${{ env.MACHINE }}
          echo '***************************************'
          echo 'DL_DIR = "/home/dev/dl"' >> ./conf/local.conf
          echo 'SSTATE_DIR = "/home/dev/sstate"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* file:///home/dev/sstate/PATH"' >> ./conf/local.conf
          echo 'SSTATE_MIRRORS += "file://.* http://sstate.yoctoproject.org/${{ env.DISTRO_VERSION }}/PATH;downloadfilename=PATH"' >> ./conf/local.conf
          echo 'IMAGE_LINGUAS = "en-us"' >> ./conf/local.conf
          echo 'FLUTTER_CHANNEL = "master"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:pn-sascha-samples = "d2d"' >> ./conf/local.conf
          echo 'PACKAGECONFIG:pn-vkcube = "kms wayland"' >> ./conf/local.conf
          echo '********** ./conf/local.conf **********'
          cat ./conf/local.conf
          echo '***************************************'
          bitbake-layers remove-layer meta-flutter
          bitbake-layers add-layer ../../meta-flutter
          bitbake-layers show-layers
          echo '***************************************'
          bitbake -e virtual/kernel | grep "^PV"
          bitbake -e virtual/kernel | grep "^PN"
          echo '***************************************'
          bitbake -e core-image-minimal | grep "^DISTRO_FEATURES"
          echo '***************************************'
          bitbake -e > bb.environment

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake core-image-minimal

      - name: Build swiftshader
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake swiftshader
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/swiftshader-git*.rpm /home/dev/artifacts

      - name: Publish swiftshader artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swiftshader-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build rpi-vk-driver
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake rpi-vk-driver
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/rpi-vk-driver-git*.rpm /home/dev/artifacts

      - name: Publish rpi-vk-driver artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rpi-vk-driver-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vkmark
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vkmark
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vkmark-git*.rpm /home/dev/artifacts

      - name: Publish vkmark artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vkmark-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vulkan-validationlayers
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vulkan-validationlayers
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vulkan-validationlayers-1.2.182-*.rpm /home/dev/artifacts

      - name: Publish vulkan-validationlayers artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vulkan-validationlayers-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vkcube
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vkcube
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vkcube-git*.rpm /home/dev/artifacts

      - name: Publish vkcube artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vkcube-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vkquake3
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vkquake3
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vkquake3-git*.rpm /home/dev/artifacts

      - name: Publish vkquake3 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vkquake3-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vkrunner
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vkrunner
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vkrunner-git*.rpm /home/dev/artifacts

      - name: Publish vkrunner artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vkrunner-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vk-layer-perfdoc
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vk-layer-perfdoc
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vk-layer-perfdoc-git*.rpm /home/dev/artifacts

      - name: Publish vk-layer-perfdoc artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vk-layer-perfdoc-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build vulkan-extensionlayer
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake vulkan-extensionlayer
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/vulkan-extensionlayer-1.2.182-*.rpm /home/dev/artifacts

      - name: Publish vulkan-extensionlayer artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vulkan-extensionlayer-rpi4-64
          path: |
             /home/dev/artifacts/*.rpm
             
      - name: Build sascha-samples (D2D)
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake sascha-samples
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/sascha-samples-git*.rpm /home/dev/artifacts

      - name: Publish sascha-samples artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sascha-samples-d2d-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-engine-release
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-engine-release -c do_cleansstate
          bitbake flutter-engine-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-engine-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-engine-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-engine-release-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-pi-release
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-pi-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-pi-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-pi-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-pi-release-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build flutter-gallery-release
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          bitbake flutter-sdk-native -c do_cleansstate
          bitbake flutter-gallery-release -c do_cleansstate
          bitbake flutter-gallery-release
          rm -rf /home/dev/artifacts/*
          cp tmp/deploy/rpm/cortexa7t2hf_neon_vfpv4/flutter-gallery-release-git*.rpm /home/dev/artifacts

      - name: Publish flutter-gallery-release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-gallery-release-rpi3
          path: |
             /home/dev/artifacts/*.rpm

      - name: Build core-image-minimal
        shell: bash
        working-directory: ../rpi3-32-drm-honister-latest
        run: |
          . ./sources/poky/oe-init-build-env ${{ env.MACHINE }}
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " flutter-pi-release"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " flutter-gallery-release"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " swiftshader"' >> ./conf/local.conf          
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " rpi-vk-driver"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " sascha-samples"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkcube"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkmark"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkquake3"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vkrunner"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vk-layer-perfdoc"' >> ./conf/local.conf
          echo 'CORE_IMAGE_EXTRA_INSTALL:append = " vulkan-extensionlayer"' >> ./conf/local.conf
          bitbake core-image-minimal
          rm -rf /home/dev/artifacts/*
          cp bb.environment /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi3/core-image-minimal-raspberrypi3.wic.bmap /home/dev/artifacts
          cp tmp/deploy/images/raspberrypi3/core-image-minimal-raspberrypi3.wic.bz2 /home/dev/artifacts

      - name: Publish SD card image artifact
        uses: actions/upload-artifact@v2
        with:
          name: rpi3-drm-flutter-release-honister-sdimage
          path: |
             /home/dev/artifacts/*
