name: kirkstone-workspace

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
  release:
    types: [ published, created, edited ]
  workflow_dispatch:
  schedule:
    # daily
    - cron:  '0 0 * * *'

jobs:

  kirkstone-workspace-matrix:

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        # macos-10.15, macos-11, macos-12, ubuntu-18.04,

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup workspace
        run: |
          FLUTTER_WORKSPACE=`pwd`/workspace
          mkdir $FLUTTER_WORKSPACE && pushd $FLUTTER_WORKSPACE
          sudo ../tools/setup_flutter_workspace.py --workspace-cfg=../tools/flutter_workspace_config.json
          popd
          sudo chown -R $USER:$USER $FLUTTER_WORKSPACE
          ls -la $FLUTTER_WORKSPACE/app

      - name: Source Environment
        shell: bash
        working-directory: workspace
        run: |
          cat ./setup_env.sh
          source ./setup_env.sh
